project:
  type: website
  output-dir: docs  # Publishes to /docs for GitHub Pages
  
format:
  html:
    logo: images/gw_horizontal_2c_rev.png
    theme:
      light: cosmo
      dark: cosmo
    css: styles.css
    include-in-header:
      - scripts/default-dark.js
    include-after-body:
      - scripts/theme-toggle.js
      - scripts/sidebar-collapse.js
      - scripts/collapse-active-section.js
    toc: true
    toc-location: left
    toc-title: Contents
    html-math-method: katex

editor: visual
      
website:
  title: "R for MSBA"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Beginning a Project"
        href: preface.qmd
        contents:
          - href: preface.qmd#choosing-an-app
            text: "Choosing an app"
          - href: preface.qmd#step-1-make-an-rstudio-project
            text: "Step 1: Make an RStudio Project"
          - href: preface.qmd#step-2-start-an-r-file
            text: "Step 2: Start an R File"            
      - text: "R syntax"
        href: syntax.qmd
        contents:
          - href: syntax.qmd#basics
            text: "Basics"
          - href: syntax.qmd#variables-a.k.a.-objects
            text: "Variables"
          - href: syntax.qmd#comments
            text: "Comments"
          - href: syntax.qmd#functions
            text: "Functions"
      - text: "Data Types and Data Structures"
        href: data_types.qmd
        contents:
          - href: data_types.qmd#basic-data-types
            text: "Basic data types"
          - href: data_types.qmd#vectors
            text: "Vectors"
          - href: data_types.qmd#matrices
            text: "Matrices"
          - href: data_types.qmd#mixing-types-in-vectors-or-matrices
            text: "Mixing types in vectors or matrices"
          - href: data_types.qmd#coercion
            text: "Coercion"
          - href: data_types.qmd#lists
            text: "Lists"
      - text: "Data Frames"
        href: data_frames.qmd
        contents:
          - href: data_frames.qmd#constructing-a-data-frame
            text: "Constructing a data frame"
          - href: data_frames.qmd#accessing-elements-of-a-data-frame
            text: "Accessing elements of a data frame"
          - href: data_frames.qmd#binding-data-frames-together
            text: "Binding data frames together"
      - text: "Factors"
        href: factors.qmd
        contents:
          - href: factors.qmd#categorical-data
          - text: "Categorical Data"
          - href: factors.qmd#the-forcats-library
            text: "The forcats library"
      - text: "Logical tests"
        href: logical_tests.qmd
      - text: "Functions"
        href: functions.qmd
        contents:
          - href: functions.qmd#using-functions
            text: "Using functions"
          - href: functions.qmd#making-your-own-functions
            text: "Making your own functions" 
          - href: functions.qmd#vectorized-functions-in-r
            text: "Vectorized functions"
      - text: "Importing and Exporting Data"
        href: import_export.qmd
        contents:
          - href: import_export.qmd#text-based-formats
            text: "Text-based formats"
          - href: import_export.qmd#excel
            text: "Excel"
          - href: import_export.qmd#other-statistical-software
            text: "Other Statistical Software"
          - href: import_export.qmd#exporting-data
            text: "Exporting data"
      - text: "Packages in R"
        href: packages.qmd
        contents:
          - href: packages.qmd#installing-packages
            text: "Installing packages"
          - href: packages.qmd#loading-packages
            text: "Loading packages"
          - href: packages.qmd#using-functions-from-packages
            text: "Using functions from packages"
      - text: "Data cleaning"
        href: data_cleaning.qmd
        contents:
          - href: data_cleaning.qmd#cleaning-up-column-names
            text: "Cleaning up column names"
          - href: data_cleaning.qmd#missing-data
            text: "Missing data"
      - text: "Data wrangling"
        href: data_wrangling.qmd
        contents:
          - href: data_analysis.qmd#selecting-columns
            text: "Selecting columns"
          - href: data_analysis.qmd#filtering-rows
            text: "Filtering rows"
          - href: data_analysis.qmd#arranging-rows
            text: "Arranging rows"
          - href: data_analysis.qmd#mutating-columns
            text: "Mutating columns"
          - href: data_analysis.qmd#joining-data-frames
            text: "Joining data frames"
          - href: data_wrangling.qmd#pivoting
            text: "Pivoting"
      - text: "Data analysis"
        href: data_analysis.qmd
        contents:
          - href: data_analysis.qmd#summary-statistics
            text: "Summary statistics"
          - href: data_analysis.qmd#grouped-summary-statistics
            text: "Grouped summary statistics"
          - href: data_analysis.qmd#statistical-tests
            text: "Statistical tests"
      - text: "Data visualization"
        href: data_visualization.qmd
        contents:
          - href: data_visualization.qmd#the-grammar-of-graphics
            text: "The grammar of graphics"
          - href: data_visualization.qmd#common-geoms
            text: "Common geoms"
          - href: data_visualization.qmd#aesthetic-mappings
            text: "Aesthetic mappings"
          - href: data_visualization.qmd#faceting
            text: "Faceting"
          - href: data_visualization.qmd#themes
            text: "Themes"
      - text: "Downloads - sample data"
        href: data.qmd
        contents:
           - href: data.qmd#downloads-for-this-workshop
             text: "Workshop downloads"
      - text: "Resources"
        href: resources.qmd
  
