---
title: "Importing and Exporting Data"
format:
  html:
    toc: false
---

# Text-based formats

Text-based data formats are very common, because they are human-readable, they don't require any special software to read, and they can be read in by many different programming languages.  Text-based formats include CSV (comma-separated values) and its variants such as TSV (tab-separated values), JSON (JavaScript Object Notation), YAML, and XML.

We're going to focus on tabular formats such as CSV; by tabular, we mean that the data represented in the file is in a table format, with rows and columns.  In a CSV, values going across a row are separated by commas; there can be other variants (such as TSV) that use a different character as a separator.

A raw CSV file might look something like this:

```
Time,Country Name,Country Code,GDP (current US$) [NY.GDP.MKTP.CD],"Population, total [SP.POP.TOTL]","Life expectancy at birth, total (years) [SP.DYN.LE00.IN]"
2014,Gabon,GAB,18203966896,1978399,66.07
2014,"Gambia, The",GMB,1229461721,2164528,62.576
2014,Georgia,GEO,17966015109,3719414,73.105
...
```

In R, we can read such a file into our environment using the `read.csv()` function.  Here's how it might look:



## Challenge:

Write code to read in a file from a file named `mydata.csv` located in your project's `data` folder.

<details>

<summary>Solution</summary>

``` r
# Read a CSV file
data <- read.csv("data/mydata.csv")
head(data)
```

</details>

# Excel

# Other statistical software
