---
title: "Introduction"
format:
  html:
    toc: false
    css: styles.css
---

# Welcome to R for MSBA!  

This is a 2-half-day course designed to prepare you with the R skills that you will need to begin the GW Master of Science in Business Analytics program.

To maximize your learning in this workshop, I recommend that you spend most of your time in RStudio trying to replicate the code that I'm showing you, and of course trying the coding challenges. The value of this site is mainly for you to have something to refer back to later.

# Instructor

### Dan Kerchner

I work as a Senior Software Developer for GW Libraries and Academic Innovation. I'm also a PhD student in the GW Milken School of Public Health, in the Health Data Science, Bioinformatics program.

# Other resources

I maintain GW Libraries' "best-of" list of R resources, which you can find at [https://libguides.gwu.edu/Rstats](https://libguides.gwu.edu/Rstats){target="_blank"}. Let me know if you have any suggestions.

# Workshop materials